[default]
exclude = [
    "stellarlend-client",
]
exclude-files = [
    "client/**/*",
    "indexing_system/**/*",
    "contracts/amm/**/*",
    "**/target_check/**/*",
    "**/examples/**/*",
    "**/fuzz/**/*"
]

